### ISSUE TITLE
Request: Love2D Android app ability to import and store .love files in its own directory (similar to iOS version)

### ISSUE THREAD

**Issue by SugarRayLua** [love2d/love#2023] opened 2024-02-20 17:34 UTC
Would be helpful to organize .love files. Understood that Android restricts access to app files but having the ability for the app to import such folders and delete them if needed would be very useful.

Thanks for considering!

**Comment by MikuAuahDark** [comment] 2024-02-21 02:03
Duplicate of love2d/love-android#219.

This has been implemented, however the directory itself is only accessible through MTP. It's in `Internal Storage/Android/data/org.love2d.android/files/games`.

**Closed by MikuAuahDark** 2024-02-21 02:03 UTC
Labels: Android

**Comment by SugarRayLua** [comment] 2024-02-22 02:13
Okay, thank you for the info. Sounds similar to the old way that iOS Love2D imported files (from iTunes) rather than newer alternative with iOS Love2D's ability to "openInPlace" and use its own Apple granted "documents" directory to store and access .love files.

**Comment by MikuAuahDark** [comment] 2024-02-22 03:05
There's also option to let user pick .love file to load (available in LOVE 11.x as built-in LOVE Loader app). There's no Android equivalent of what you described, but the option I mentioned is close enough.

**Comment by MikuAuahDark** [comment] 2024-02-22 09:23
Yes that one is LOVE 12.
