### ISSUE TITLE
Feature Request - Signed Distance Field Fonts

### ISSUE THREAD

**Issue by kruncher** [love2d/love#1660] opened 2021-01-03 06:44 UTC
It would be fantastic if love2d supported SDF text rendering out-of-the-box similar to what Unity provides with TextMesh Pro providing the advantage of being able to render sharp text at various scales.

**Comment by flamendless** [comment] 2021-01-03 07:36
You could use this https://github.com/Tjakka5/love-sdf-text

**Comment by slime73** [comment] 2021-01-03 13:19
Duplicate of #1392

**Closed by slime73** 2021-01-03 13:19 UTC
