### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by dmekersa** [love2d/love#1777] opened 2022-02-18 10:45 UTC
The Love2D website is down for 48h now.

**Comment by zombrodo** [comment] 2022-02-18 10:54
see: https://github.com/love2d/website/issues/11#issuecomment-1043610978

**Comment by MikuAuahDark** [comment] 2022-02-18 11:37
Duplicate of [love2d/website#11](https://github.com/love2d/website/issues/11#issuecomment-1043610978)

**Closed by MikuAuahDark** 2022-02-18 11:37 UTC
