### ISSUE TITLE
hidpi config option has no effect

### ISSUE THREAD

**Issue by expikr** [love2d/love#1952] opened 2023-07-07 10:29 UTC
Surface Pro 4, 200% scale.

```lua
function love.conf(t)
    t.window.depth = 16
    t.window.highdpi = true
end
```

Game still renders at low dpi.

**Comment by slime73** [comment] 2023-07-07 11:00
Duplicate of #1421

SDL2 didn't support high DPI on Windows at all until recently, and the new support uses a new API which doesn't really allow changing it at runtime after initial setup. So [love 12](https://love2d.org/wiki/12.0) adds support for high DPI on Windows and changes its APIs for it to be a `t.highdpi` flag instead of `t.window.highdpi` and a `love.window.setMode` flag.

**Closed by slime73** 2023-07-07 11:00 UTC

**Comment by slime73** [comment] 2023-07-07 21:08
It's not, since SDL3 doesn't have a stable API or ABI yet and doesn't have a released version (and might not for a while).
