### ISSUE TITLE
LOVE 12: Crash when drawing TextBatch objects

### ISSUE THREAD

**Issue by JamesVanBoxtel** [love2d/love#1914] opened 2023-03-30 04:42 UTC
When trying to upgrade Panel Attack (panelattack.com) to love 12, we are getting crash when drawing a TextBatch object sometimes. Sometimes it happens sometimes it doesn't. I have included a trimmed down version that seems to crash on launch on my macOS system.

Error

Stack Trace: 
    graphics_util.lua:294: in function 'menu_draw'
    click_menu.lua:342: in function 'functionObject'
    main.lua:189: in function 'draw'
    CustomRun.lua:115: in function 'pa_runInternal'
    CustomRun.lua:173: in function <CustomRun.lua:171>
    [C]: in function 'xpcall'
Username: defaultname
Theme: Panel Attack Modern
Error Message: graphics_util.lua:294: Textures with non-readable formats cannot be sampled from in a shader.
Engine Version: 047
Build Version: Unknown
Operating System: OS: OS X
Love Version: 12.0.0
UTC Time: 2023-03-30 04:33:03

Steps to reproduce:
1. Extract the following code to a folder:
[PALove12Crash.zip](https://github.com/love2d/love/files/11107795/PALove12Crash.zip)
2. Navigate to the folder and run love 12 with the current directory
3. click to go to the main menu
4. if the game doesn't crash with the error above, repeat step 2 and 3

**Comment by slime73** [comment] 2023-04-01 19:27
I ran this about 20 times each on my Mac and Windows machine and couldn't reproduce the issue at all. Where did you get your love 12 build, and how recent is it? Also what's your computer's model and OS version?

**Comment by slime73** [comment] 2023-04-02 18:38
I grabbed the latest macOS build from github, updated my M1 Mac to the latest macOS version (13.3) and ran the project there with the given steps and haven't been able to reproduce it on that computer either. Maybe something needs to happen to reproduce it that isn't listed in the repro steps?

**Comment by slime73** [comment] 2023-04-23 01:00
I reproduced this via a separate issue report (#1922), I've committed a fix in [90b22f7](https://github.com/love2d/love/commit/90b22f7d42f953dbf4a2bc720b4a6e7d4b8c7b5a).

**Closed by slime73** 2023-04-23 01:00 UTC
Labels: bug
