### ISSUE TITLE
Bad performance while using OGV video format

### ISSUE THREAD

**Issue by literalmente-game** [love2d/love#1726] opened 2021-09-03 14:51 UTC
This is an issue that I've found to be true for most projects that use OGV (also verified with the https://github.com/adventuregamestudio engine). There's no issue until you need to use good quality video (higher bitrate or resolution, doesn't matter much, as even something as "high" as 720p at a poor bitrate sometimes will just skip frames and not run smooth at all).

To have a video usable on Löve with OGV, I had to make absurd compromises (extremely low bitrates, very low resolution and even had to cut the framerate by 3). Just to be clear, when I say "usable", I mean "able to be played correctly without skipping frames or stuttering".
This also isn't a performance issue, my GPU (GTX 1050 TI) can handle any other video format in much higher resolutions with no problems, OGV gives playback issues at avg resolutions with the same GPU even running from a fast SSD.

As seen on Adventure Game Studio forums, no one actually have a solution for this (every single user that had this issue gave up and had to make the same compromises I did, killing the video quality), so maybe support for another (perhaps more common and popular format, such as MP4) could be implemented?

**Comment by MikuAuahDark** [comment] 2021-09-03 15:11
To be honest, Theora (I'll refer OGV as Theora from now on) is not the best video codec out there, but before AV1 existed (see #1625), that's the only available video codec that can be added without having to deal with patents that H264 (and H265) has. All the decoding is done using CPU so if the video bitrate is high, your CPU may struggle decoding the frames.

**Comment by literalmente-game** [comment] 2021-09-03 15:36
> All the decoding is done using CPU so if the video bitrate is high, your CPU may struggle decoding the frames

I saw many cases where even _very_ high end CPUs had performance issues with low bitrates at 1080p, so Theora is probably the issue, not any specific hardware. There's no other codec available or maybe the option to allow users to load other codecs as "plugins"?

**Comment by slime73** [comment] 2021-09-03 15:53
> Edit: any chances for AV1 support by 12.0 release?

Not likely unless someone wants to contribute that work themselves.

**Comment by slime73** [comment] 2021-09-03 15:55
Duplicate of #1625

**Closed by slime73** 2021-09-03 15:55 UTC
