### ISSUE TITLE
Can't Launch Löve on AwesomeWM (Arch Linux)

### ISSUE THREAD

**Issue by pinguftw2** [love2d/love#1694] opened 2021-05-03 13:52 UTC
`X connection to :0 broken (explicit kill or server shutdown).`
Arch Linux awesomewm
with xf86-video-intel and picom

**Comment by thisnickwasfree** [comment] 2021-05-09 19:28
Well, xmonad works without any problem…
When I've launced Awesome some years ago it wanted patched XCB. So, may be this can be the reason?
Another thing… Some parts of X/Xlib may be not installed due to Awesome is using XCB, not Xlib. So, try to trace what lib is missing for love. Or just install OpenBox or other light-weight wm with all X-dependencies (may be Awesome ll be able to launch love with them).

**Comment by pinguftw2** [comment] 2021-05-09 21:05
Thanks for your reply. If I get a result, I'll let you know.

**Comment by slime73** [comment] 2021-05-15 14:16
Since this seems like a system configuration problem rather than something to do with LÖVE's source code I'm closing the issue – if you need more help figuring it out the forums or discord server might be able to provide assistance.

**Closed by slime73** 2021-05-15 14:16 UTC

**Comment by harshetmaruff** [comment] 2021-07-19 19:55
I have this same problem when launching love in manjaro 21.1.0 kde

**Comment by localhost-sys** [comment] 2022-02-06 12:45
I tried appimage file on XFCE. It comes with the same error.

**Comment by MikuAuahDark** [comment] 2022-02-06 13:24
Since I can't really reproduce this in ArchLinux with KDE, maybe https://github.com/yuq/xtrace worth to try to see what's going on.
