### ISSUE TITLE
Love stops updating graphics after coming back from hibernation

### ISSUE THREAD

**Issue by alejandro-alzate** [love2d/love#1977] opened 2023-10-05 12:31 UTC
How to reproduce
1. Open a game
2. hibernate your computer
3. power on your computer
4. profit

Actual behavior
- Games continues to function but the graphics are frozen.

Expected behavior
- Graphics continue to funtion

System
- Windows 10 Pro
- 64 bit
- 22H2
- 8GB DDR3 Ram
- I5-4460S CPU @ 2.90GHz   2.90 GHz
- IGD Intel HD 4600 (Active, for the quick sync decoder, sometimes i use the monitor at 1280x1024@75 sometimes but never used to reproduce the bug.)
- GPU XFX RADEON HD 66850 (Atcive, main monitor on DVI-I 1440x900@60 used to reproduce the bug, and what love uses, idk really how love picks its gpu, i actually want to know that logic, i do wonder if i can modify it to use the IGD other GPU or what)
- More graphics info by the game itself: ![1696508767](https://github.com/love2d/love/assets/57909935/c8afed87-ca4c-4409-b0e1-946aa57e8741)

**Comment by slime73** [comment] 2023-10-05 21:24
I haven't been able to reproduce this problem on my Windows 10 computer with an nvidia 1070 GPU. I used the no-game screen to test.

It's probably a bug inside AMD's graphics drivers. If you've tested with AMD's latest driver version then you might want to report the bug to AMD. They've fixed other driver bugs that have affected love in the past after people have reported them.

Since this isn't a problem that's caused by or fixable in love's source code I'll close this issue.

> idk really how love picks its gpu, i actually want to know that logic, i do wonder if i can modify it to use the IGD other GPU or what)

Graphics drivers on Windows don't provide a convenient way for an app to choose which GPU to use when booting up when OpenGL is used, unfortunately. They do look for this but it can't be modified without recompiling the exe: https://github.com/love2d/love/blob/2deb6273c2588c7dd008daed7f15a627d8b880e4/src/love.cpp#L52-L60

On systems with both a high- and low-power GPU the graphics driver UI might have a way to select one GPU or the other as the preferred one though, but apps can't make use of that, only users can.

**Closed by slime73** 2023-10-05 21:24 UTC

**Comment by alejandro-alzate** [comment] 2023-10-05 23:58
ok. i have nothing to argue i mean my gpu is very ancient

**Comment by MikuAuahDark** [comment] 2023-10-06 03:05
In Windows, GPU selection is done through Windows Settings.

**Comment by alejandro-alzate** [comment] 2023-10-08 06:07
i do know that exist (correct me if im wrong) isn't the default that let the app chooses? (i might check tomorrow since is late here)
Any other platform like linux can let you choose within the app to choose?
like those games that can use two or more **including** igd. what's the roadblock?
