### ISSUE TITLE
setEffect (reverb in this case) causes strange drop in source volume

### ISSUE THREAD

**Issue by Schwegg** [love2d/love#1732] opened 2021-10-05 19:47 UTC
I've run into an issue which I only recently noticed which seems to involve applying an effect, in my specific case applying 'reverb' and then disabling the effect. I originally thought this only happened when applying an effect onto multiple sources and then disabling said effect, but it seems after some testing that it's more-so if an effect is applied onto a source and then disabled/removed. I assume it's happening because the effect 'lingers'.

I find it very strange strange that it still applies even if the source is stopped, the effect removed and then played again? eg.
```Lua
local time = source:tell( "seconds" )
source:stop()
source:setEffect( "reverb", false )
source:seek( time )
source:play()
```

the volume itself when using `source:getVolume()` doesn't change, but the volume itself does? which I assume to be from the effect, but it doesn't make sense why it lingers after.

using: Love2d 11.3
OS: Windows10

**Comment by devenvexe** [comment] 2023-01-12 06:14
Nercomancing this issue as I was playing around with audio in my game. 

I can't reproduce any perceived attenuation in playback audio when disabling an effect in love 12. I used this simple test case:

```
local wet = false
function love.load()
    local res = love.audio.setEffect("reverb", {type="reverb"})
    print("Effect creation is " .. (res and "true" or "false"))
    
    snd = love.audio.newSource("swag.wav", "static")
    print("Playing dry")
    snd:play()
end

function love.update(dt)
    if not snd:isPlaying() then
        wet = not wet
        snd:seek(0)
        if wet then
            print("Playing with reverb")
            snd:setEffect("reverb" ,true)
            snd:play()
        else
            print("playing dry")
            snd:setEffect("reverb" ,false)
            snd:play()
        end
    end
end
```

I recommend closing this issue if there isn't any further repro info.

**Comment by slime73** [comment] 2023-01-12 18:26
Thanks for testing! love 12 uses a newer version of OpenAL Soft on Windows, compared to love 11.3. Maybe there was a problem in the library that got fixed in between the two versions.

**Closed by slime73** 2023-01-12 18:26 UTC
