### ISSUE TITLE
Physics problems before first `world:update` on ARM

### ISSUE THREAD

**Issue by Tsugiru** [love2d/love#1859] opened 2022-10-30 22:57 UTC
I've basically already discussed this on the [official forums](https://love2d.org/forums/viewtopic.php?f=4&t=93825), but I'll reiterate it here.

> Hello,

> I'm learning love2d and I've been tinkering with some things. There is one thing that confuses me, namely, it seems like physics properties like velocity (but also forces and impulses) have different effects when applied to entities before after the first `world:update`. Is there a reason for this? This makes it hard to set proper "initial state" for the game, as one has to wait until the world executes a single update, and then apply physics properties to objects.

> Consider this example:

```
-- main.lua
local world = love.physics.newWorld(0, 0)

local entity = {}
entity.body = love.physics.newBody(world, 200, 200, 'dynamic')
entity.body:setMass(32)
-- entity.body:setLinearVelocity(500, 0)
entity.shape = love.physics.newCircleShape(0, 0, 10)
entity.fixture = love.physics.newFixture(entity.body, entity.shape)

love.draw = function()
  print(entity.body:getLinearVelocity())
  local ball_x, ball_y = entity.body:getWorldCenter() 
  love.graphics.circle('fill', ball_x, ball_y, entity.shape:getRadius())
end

local applied = false

love.update = function(dt)
  world:update(dt)
--  if not applied then 
--    entity.body:setLinearVelocity(500, 0)
--    applied = true
--  end
end
```

> If I run this main.lua locally, applying the velocity on the entity in the global scope prints 188.86 (rounded) in the love.draw function, however, applying it in the love.update function after world:update prints the correct velocity, 500.

Some additional information:
Love version: LÖVE 11.4 [Mysterious Mysteries]
OS: macOS Monterey 12.4
Chip: Apple M1 ARM

**Comment by ImagicTheCat** [comment] 2022-11-19 13:57
Hi,

I could reproduce the issue by doing a large step like `world:update(0.4)` once. The initial delta time is probably high.

**Comment by slime73** [comment] 2023-01-15 03:28
On macOS the first love.event.pump call (inside the first frame) takes a long time (about 350ms for me), apparently. I'm not sure if we should try to work around it or not though 🤔

**Comment by ImagicTheCat** [comment] 2023-01-15 15:37
I think it would be better to have two different functions:
- The current one would be the low-level match to a Box2D step.
- A new one would create an abstraction for a fixed time step simulation with arbitrary input time (this is recommended for physics engine).

The current `update` function seems to be used as would the abstraction above, causing issues.

**Comment by slime73** [comment] 2023-01-15 15:40
A fixed-timestep update function comes with a whole lot of baggage that adds complexity to user code (for example users have to interpolate states when drawing otherwise things can look like they're stuttering on different systems).

I don't think it's necessarily out of the question for the future, but it's a feature request that needs careful thought put into it rather than an immediate fix for this issue.

**Closed** 2023-01-15 16:36 UTC
Labels: 11.4, library dependency
