### ISSUE TITLE
updateMode/setMode behaviour differs from 11.5

### ISSUE THREAD

**Issue by Endaris** [love2d/love#2114] opened 2024-10-22 22:42 UTC
The window position updates in some odd and not quite predictable ways in love 12 using SDL3.
The expected outcome for the following repro is that the window stays centered at all times and modifies its position.
I am able to verify this with the 11.5 release as well as the output of a 12.0 CI run before the SDL3 adoption.

On my machine, using the CI build [from 2 days ago](https://github.com/love2d/love/actions/runs/11428313547), the first updateMode does not change the window position.
The second updateMode changes the window position but the new position is not centered on the display.

Repro main.lua:
```Lua
local resize1 = false
local resize2 = false

function love.load()
  love.window.setMode(800, 600, { resizable = true, centered = true})
end

function love.update()
  if not resize1 and love.timer.getTime() > 4 then
    love.window.updateMode(640, 480)
    resize1 = true
  elseif not resize2 and love.timer.getTime() > 7 then
    love.window.updateMode(300, 480)
    resize2 = true
  end
end

function love.draw()
  love.graphics.print("resize1: " .. tostring(resize1), 10, 10)
  love.graphics.print("resize2: " .. tostring(resize2), 10, 30)
end
```

My machine uses debian 12
love.graphics.getRendererInfo output:
OpenGL;4.3.0 NVIDIA 535.183.01;NVIDIA Corporation;NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by slime73** [comment] 2024-10-26 14:45
I haven't been able to reproduce the issue, but I don't have a Linux machine to test on. Can you see if [d099da1](https://github.com/love2d/love/commit/d099da1e3b8f7dd4c9c23b6b471ec5ffd8ddcc10) fixed it for you?

**Comment by MadByteDE** [comment] 2024-10-29 12:07
Fedora 41, Wayland, KDE 6.2
`OpenGL  4.3.0 NVIDIA 560.35.03  NVIDIA Corporation      NVIDIA GeForce RTX 4070/PCIe/SSE2`

I can confirm that on my Linux machine, the provided code does indeed have different results in resizing between love11 and love12. used the latest action `appImage` build for love12 with the position fix.

[Screencast_20241029_125837.webm](https://github.com/user-attachments/assets/3cb18ba6-6d76-4e90-945f-6c8e5e26dd6a)

love11 keeps centred while love12 does not.

**Comment by slime73** [comment] 2024-11-11 17:53
Can you try the latest build? It uses an updated version of SDL3 – I haven't really seen any code changes to it that might affect things, but it's still worth a try I think.

**Comment by Endaris** [comment] 2024-11-11 20:21
Behaviour did not change unfortunately

**Comment by slime73** [comment] 2024-11-11 20:24
Since the repro has `resizable = true`, does that mean it doesn't happen when the window is not user-resizable?

**Comment by Endaris** [comment] 2024-11-11 20:30
No, the same thing happens actually. I think I initially added it because the context in which I first encountered the issue relied on that.
I don't remember why I stopped trying to get the repro even smaller.

**Comment by slime73** [comment] 2024-12-26 00:57
Do you mind testing again with the latest build? It uses an updated SDL3 again which had a bunch of window state-related changes recently.

**Comment by MadByteDE** [comment] 2024-12-26 07:59
Same issue for me with the latest build.

**Comment by slime73** [comment] 2024-12-28 02:18
I installed WSL2 with ubuntu 24.04 and ran the latest build (as of today - it's a new build as of today compared to a few days ago because the appimage's repo uses a newly updated SDL to fix another windowing bug), and I can't reproduce the issue. It stays centered after each resize.

Can you confirm?

**Comment by slime73** [comment] 2024-12-28 02:23
Actually I can reproduce the broken behaviour with older builds, so I'm pretty sure this is fixed now.

**Closed by slime73** 2024-12-28 02:23 UTC
Labels: bug, library dependency, Linux
