### ISSUE TITLE
website https://love2d.org down for some days ?

### ISSUE THREAD

**Issue by gcmartijn** [love2d/love#1779] opened 2022-02-18 18:12 UTC
Here the website is down.

https://love2d.org

![Screenshot 2022-02-18 at 19 11 53](https://user-images.githubusercontent.com/6859464/154738968-ec5c5a92-7aa8-4e6c-8cbd-903f932c049d.png)

**Comment by slime73** [comment] 2022-02-18 18:20
https://github.com/love2d/website/issues/11#issuecomment-1043610978

**Comment by MikuAuahDark** [comment] 2022-02-19 03:06
From now on, any "Website down" issue report will be closed and locked to reduce issue tracker spam.

Duplicate of https://github.com/love2d/website/issues/11#issuecomment-1043610978

**Closed by MikuAuahDark** 2022-02-19 03:06 UTC
