### ISSUE TITLE
Get incorrect screen size on Android

### ISSUE THREAD

**Issue by heiyu17** [love2d/love#1615] opened 2020-08-17 03:52 UTC
**My Phone**
Resolution: 2340 × 1080
In Dpi-Scale: 780 × 360

```lua
function love.run
   chunk1
   return function()
   end
end
```
In chunk1 the functions of love.graphics getWidth() getHeight() and getDimensions() always get smaller screen size 2259 × 999 or 753 × 333 of the screen.

Even though i do this
```lua
function love.run
   love.window.setFullscreen(true)
   W = love.graphics.getWidth()
   H = love.graphics.getHeight()
end
```
or
```lua
function love.run
   love.load()
end

function love.load
   love.window.setFullscreen(true)
   W, H = love.graphics.getDimensions()
end
```
or
```lua
function love.conf(t)
   t.window.usedpiscale = false
end
```

In loading step I wanna define two variables `screen.w` and `screen.h` for handy.

But now I have got to do this in the first love.update of the mainloop.
```lua
function love.update
   SW, SH = love.graphics.getDimensions()
   initialization work depends on SW, SH
   love.update = love.trueupdate
end
```
Because the screen size is only got correctly in the mainloop.

And I found an alternative way.
```lua
function love.load
   -- this triggers the love.resize
   love.window.setFullscreen(true)
end

function love.resize(w, h)
   SW, SH = w, h
end
```
But there is a 15% chance that the `w` `h` got nil.

I don't know whether this is solved.
So I just post this issue here with LÖVE 11.3.

**Comment by MikuAuahDark** [comment] 2020-08-17 09:47
> In chunk1 the functions of love.graphics getWidth() getHeight() and getDimensions() always get smaller screen size 2259 × 999 or 753 × 333 of the screen.
Is the status bar appears? If so, that maybe the cause. Current version has inconsistencies with resolution when the status bar appears. However this is supposed to be fixed in love2d/love-android@31d7affd91cd5ab021b2058fd2c06b1ed593e261

> But there is a 15% chance that the `w` `h` got nil.
No, as long as `love.resize` callback is triggered, the `w` and `h` will contain the new screen resolution, and that's a guarantee by SDL.

**Comment by heiyu17** [comment] 2020-08-17 11:28
> 
> > But there is a 15% chance that the `w` `h` got nil.
> 
> No, as long as `love.resize` callback is triggered, the `w` and `h` will contain the new screen resolution, and that's a guarantee by SDL.

Under that situation the game directly crashes to a blue error screen, says: SW, SH got nil, which I only assign as the value of the arg `w` `h` in love.resize() triggered by setFullscreen().

It dosen't happen very often, and I believe if the dimension question solved, this will also be solved. Thanks for your work!

**Comment by MikuAuahDark** [comment] 2020-08-18 11:14
That may indicate `love.resize` event itself not triggered. Consider setting `SW` and `SH` to `love.graphics.getDimensions()`. Also `love.window.setFullscreen()` only triggers `love.resize` on next frame, if applicable.

**Comment by MikuAuahDark** [comment] 2021-07-18 04:13
I can't say this is a bug however and since there are no activity, I'll close the issue.

**Closed by MikuAuahDark** 2021-07-18 04:13 UTC
Labels: 11.3, more info needed
